# ---------------- #
#   Main Configs   #
# ---------------- #
title: 智能作坊
description: > # this means to ignore newlines until "baseurl:"
  专注于Android软件开发的码农,带你深入分析Android系统.目前的专题有Android编译系统,Binder机制，单元测试，深入理解Activity启动流程。
baseurl: "https://octopusy.github.io/" # the subpath of your site, e.g. /blog
url: "https://octopusy.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: octopus
github_username:  octopus

favicon: /favicon.ico
timezone: Asia/ShenZhen
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Richard
organization: XGD 
location: ShenZhen, China
email: 583206137@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#  -
#    href: /wiki/
#    label: 维基

  #-
  #   href: /links/
  #  label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
#collections:
#    wiki:
#        output: true
#        permalink: /wiki/:path/

repository: octopusy/octopusy.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: octopusy
csdn_username: zhangyang5547662

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: octopus
disqus_username: octopus
# 在使用一个时可点击显示另一个
lazy_load_another : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
